---
### Handlers file for base-server-config

- name: Enable swap on startup
  ansible.builtin.lineinfile:
    path: "/etc/fstab"
    regexp: "^/swap"
    line: '/swap none swap sw 0 0'
    state: present


- name: Reload sysctl
  ansible.builtin.shell: "sysctl -p"
  ignore_errors: true


- name: Restart journald service
  ansible.builtin.systemd_service:
    name: systemd-journald
    state: restarted


- name: Restart ufw service
  ansible.builtin.systemd_service:
    name: ufw
    state: restarted
    enabled: true


- name: Restart sshd service
  ansible.builtin.systemd_service:
    name: >-
      {%- if ansible_facts['distribution'] == 'Debian' -%}
        sshd
      {%- elif ansible_facts['distribution'] == 'Ubuntu' -%}
        ssh
      {%- else -%}
        ssh
      {%- endif -%}
    daemon_reload: true
    state: restarted


- name: Reboot system
  ansible.builtin.shell: "sleep 10 && reboot"
  async: 1
  poll: 0


- name: Delete ufw rule for default ssh port
  community.general.ufw:
    rule: allow
    port: 22
    proto: tcp
    delete: true
  when: server_config == true and ansible_facts['user_id'] == "root"


- name: Wait for online
  ansible.builtin.wait_for_connection:
    connect_timeout: 15
    sleep: 5
    delay: 40
    timeout: 300
  vars:
    ansible_port: "{{ server_ssh_port }}"
    ansible_user: "{{ user_name }}"
